### PR TITLE
add devise to app

### PR DESCRIPTION
**Pull request by mchancfy**
:D yaeh!!

### CODE REVIEW

**Review by mchancfy — COMMENTED** [review]
:D i viewed

**Comment by AdityaDeOfficial** [comment]
I saw too :)

**Comment by muttaphilly** [comment]
Interesting stuff. 10/10 kittys

**Comment by muttaphilly** [comment]
Test test hjlep

**Comment by muttaphilly** [comment]
psych. re-open

**Comment by AdityaDeOfficial** [comment]
Here we go.....

**Pull request merged**
